name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build extensions
        env:
          NODE_ENV: production
        run: pnpm run build
      - name: Pack extensions
        env:
          REPO_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        run: pnpm run repo

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
